{
 "title": "Wexhook - PromEx Phoenix Dashboard",
 "description": "All the data that is presented here is captured by the PromEx Phoenix plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/phoenix.ex)",
 "tags": [
  "PromEx",
  "Phoenix",
  "wexhook"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Prometheus Job",
    "query": "label_values(wexhook_prom_ex_prom_ex_status_info, job)"
   },
   {
    "name": "instance",
    "label": "Application Instance",
    "query": "label_values(wexhook_prom_ex_prom_ex_status_info{job=\"$job\"}, instance)"
   },
   {
    "name": "endpoint",
    "label": "Phoenix Endpoint",
    "query": "label_values(wexhook_prom_ex_phoenix_endpoint_port_info, endpoint)"
   },
   { "name": "interval", "label": "Interval", "query": "15s, 30s, 1m, 5m, 15m, 30m, 1h" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Endpoint",
   "type": "stat",
   "description": "The Phoenix Endpoint module currently active for config metrics.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "wexhook_prom_ex_phoenix_endpoint_port_info{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}"
    }
   ]
  },
  {
   "title": "Server Port",
   "type": "stat",
   "description": "The port that the server is listening on.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "wexhook_prom_ex_phoenix_endpoint_port_info{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}"
    }
   ]
  },
  {
   "title": "Server URL",
   "type": "stat",
   "description": "The URL that the server is configured to be accessed from.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wexhook_prom_ex_phoenix_endpoint_url_info{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}"
    }
   ]
  },
  {
   "title": "Apdex Score (Last 24h)",
   "type": "stat",
   "description": "The Apdex score of the app based on a satisfactory response time of 500ms and a tolerable response time of 1000ms. This only takes into account how long Phoenix has been handling the request and only requests that resulted in a 2xx status code. The score is based on the last 24 hours of requests.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n    sum(increase(wexhook_prom_ex_phoenix_http_request_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", le=\"500\", status=~\"2..\"}[24h])) + \n    (sum(increase(wexhook_prom_ex_phoenix_http_request_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", le=\"1000\", status=~\"2..\"}[24h])) - sum(increase(wexhook_prom_ex_phoenix_http_request_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", le=\"500\", status=~\"2..\"}[24h]))) / 2\n  ) \n  / \n  sum(increase(wexhook_prom_ex_phoenix_http_request_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", status=~\"2..\"}[24h]))\n) * 100"
    }
   ]
  },
  {
   "title": "Error Percentage (Last 24h)",
   "type": "stat",
   "description": "A percentage of responses that resulted in 400s or 500s over the past 24 hours.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(wexhook_prom_ex_phoenix_http_requests_total{job=\"$job\", instance=\"$instance\", status=~\"4..|5..\"}[24h])) / sum(increase(wexhook_prom_ex_phoenix_http_requests_total{job=\"$job\", instance=\"$instance\"}[24h])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Data Transferred (Last 24h)",
   "type": "stat",
   "description": "The amount of data transferred by Phoenix in a 24 hour rolling window.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(wexhook_prom_ex_phoenix_http_response_size_bytes_sum{job=\"$job\", instance=\"$instance\"}[24h]))"
    }
   ]
  },
  {
   "title": "Total Requests Received (Last 24h)",
   "type": "stat",
   "description": "The amount of requests received by Phoenix in a 24 hour rolling window.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(wexhook_prom_ex_phoenix_http_requests_total{job=\"$job\", instance=\"$instance\"}[24h])))"
    }
   ]
  },
  {
   "title": "Apdex Score (Last 1h)",
   "type": "stat",
   "description": "The Apdex score of the app based on a satisfactory response time of 500ms and a tolerable response time of 1000ms. This only takes into account how long Phoenix has been handling the request and only requests that resulted in a 2xx status code. The score is based on the previous hour of requests.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  (\n    sum(increase(wexhook_prom_ex_phoenix_http_request_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", le=\"500\", status=~\"2..\"}[1h])) + \n    (sum(increase(wexhook_prom_ex_phoenix_http_request_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", le=\"1000\", status=~\"2..\"}[1h])) - sum(increase(wexhook_prom_ex_phoenix_http_request_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", le=\"500\", status=~\"2..\"}[1h]))) / 2\n  ) \n  / \n  sum(increase(wexhook_prom_ex_phoenix_http_request_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", status=~\"2..\"}[1h]))\n) * 100"
    }
   ]
  },
  {
   "title": "Error Percentage (Last 1h)",
   "type": "stat",
   "description": "A percentage of responses that resulted in 400s or 500s over the past hour.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(wexhook_prom_ex_phoenix_http_requests_total{job=\"$job\", instance=\"$instance\", status=~\"4..|5..\"}[1h])) / sum(increase(wexhook_prom_ex_phoenix_http_requests_total{job=\"$job\", instance=\"$instance\"}[1h])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Data Transferred (Last 1h)",
   "type": "stat",
   "description": "The amount of data transferred by Phoenix in the past hour.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(wexhook_prom_ex_phoenix_http_response_size_bytes_sum{job=\"$job\", instance=\"$instance\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total Requests Received (Last 1h)",
   "type": "stat",
   "description": "The amount of requests received by Phoenix in the past hour.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(wexhook_prom_ex_phoenix_http_requests_total{job=\"$job\", instance=\"$instance\"}[1h])))"
    }
   ]
  },
  { "title": "HTTP Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request Time",
   "type": "heatmap",
   "description": "A heatmap showing the request time spread across all requests (regardless of path).",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(irate(wexhook_prom_ex_phoenix_http_request_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Response Payload Size",
   "type": "heatmap",
   "description": "A heatmap showing the response payload size spread across all requests (regardless of path).",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(irate(wexhook_prom_ex_phoenix_http_response_size_bytes_bucket{job=\"$job\", instance=\"$instance\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Average HTTP Request Time",
   "type": "graph",
   "description": "The average request time per path per status code per HTTP method.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ms", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "sum(irate(wexhook_prom_ex_phoenix_http_request_duration_milliseconds_sum{job=\"$job\", instance=\"$instance\"}[$interval])) by(path, status) / sum(irate(wexhook_prom_ex_phoenix_http_request_duration_milliseconds_count{job=\"$job\", instance=\"$instance\"}[$interval])) by(path, status)",
     "legendFormat": "{{ method }} {{ path }} :: {{ status }}"
    }
   ]
  },
  {
   "title": "Average HTTP Response Size",
   "type": "graph",
   "description": "The average response size per path per status code per HTTP method.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "decbytes", "label": "Response Size" }
   ],
   "targets": [
    {
     "expr": "sum(irate(wexhook_prom_ex_phoenix_http_response_size_bytes_sum{job=\"$job\", instance=\"$instance\"}[$interval])) by(path, status) / sum(irate(wexhook_prom_ex_phoenix_http_response_size_bytes_count{job=\"$job\", instance=\"$instance\"}[$interval])) by(path, status)",
     "legendFormat": "{{ method }} {{ path }} :: {{ status }}"
    }
   ]
  },
  {
   "title": "Path Requests",
   "type": "graph",
   "description": "Shows the number of requests coming into certain paths and the resulting response codes.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "locale", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "irate(wexhook_prom_ex_phoenix_http_requests_total{job=\"$job\", instance=\"$instance\"}[$interval])",
     "legendFormat": "{{ method }} {{ path }} :: {{ status }}"
    }
   ]
  },
  {
   "title": "Response Status Codes",
   "type": "graph",
   "description": "The aggregate response status of all the requests.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(irate(wexhook_prom_ex_phoenix_http_requests_total{status=~\"2..\", job=\"$job\", instance=\"$instance\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(irate(wexhook_prom_ex_phoenix_http_requests_total{status=~\"4..\", job=\"$job\", instance=\"$instance\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(irate(wexhook_prom_ex_phoenix_http_requests_total{status=~\"5..\", job=\"$job\", instance=\"$instance\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "Channel Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Channel Join Events",
   "type": "graph",
   "description": "How many channel joins have occurred over time.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "Channel joins" }
   ],
   "targets": [
    {
     "expr": "irate(wexhook_prom_ex_phoenix_channel_joined_total{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$interval])",
     "legendFormat": "{{ transport }} :: {{ result }}"
    }
   ]
  },
  {
   "title": "Channel Message Handle Time",
   "type": "heatmap",
   "description": "A heatmap showing the request time spread across all channel events.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum(irate(wexhook_prom_ex_phoenix_channel_handled_in_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Average Channel Response Time",
   "type": "graph",
   "description": "The average response time for a channel message.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "ms", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "irate(wexhook_prom_ex_phoenix_channel_handled_in_duration_milliseconds_sum{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$interval]) / irate(wexhook_prom_ex_phoenix_channel_handled_in_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$interval])",
     "legendFormat": "{{ transport }} :: {{ result }}"
    }
   ]
  },
  { "title": "Socket Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Socket Connection Events",
   "type": "graph",
   "description": "How many socket connections have occurred over time.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short", "label": "Channel joins" }
   ],
   "targets": [
    {
     "expr": "irate(wexhook_prom_ex_phoenix_socket_connected_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$interval])",
     "legendFormat": "{{ transport }} :: {{ result }}"
    }
   ]
  },
  {
   "title": "Socket Connection Time",
   "type": "heatmap",
   "description": "A heatmap showing the request time spread across all socket connections.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "sum(irate(wexhook_prom_ex_phoenix_socket_connected_duration_milliseconds_bucket{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Average Socket Connection Time",
   "type": "graph",
   "description": "The average time it connects to establish a socket connection.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "ms", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "irate(wexhook_prom_ex_phoenix_socket_connected_duration_milliseconds_sum{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$interval]) / irate(wexhook_prom_ex_phoenix_socket_connected_duration_milliseconds_count{job=\"$job\", instance=\"$instance\", endpoint=\"$endpoint\"}[$interval])",
     "legendFormat": "{{ transport }} :: {{ result }}"
    }
   ]
  }
 ]
}